#!/bin/bash

script=$(readlink -f $0)
scriptdir=$(dirname $script)
vimplgs=$HOME/.vim
cache=$HOME/.cache
installd=$HOME/.local/bin

function usage () {
	echo "Usage:"
	echo "install -i (install)"
	echo "install -c (clean install)"
	echo "install -u (update vimplugin)"
	echo "install -r (uninstall)"
	echo "install -h (help)"
	[[ -n $1 ]] && exit $1
	exit
}

function install () {
	mkdir -p $installd 
	mkdir -p $cache
	mkdir -p $vimplgs/autoload
	mkdir -p $vimplgs/bundle
	mkdir -p $installd
	cp -T $scriptdir/vimplugin $installd/vimplugin
	curl -LsSo $vimplgs/autoload/pathogen.vim https://tpo.pe/pathogen.vim
	exit
}

function uninstall () {
rm -rf $vimplgs
	exit
}

function update() {
	mkdir -p $installd
	cp -T $scriptdir/vimplugin $installd/vimplugin 
	exit
}

while getopts ":icruh" flag; do
	case $flag in
		i)
			install
			;;
		c)
			rm -rf $vimplgs
			install
			;;
		r)
			uninstall
			;;
		u)
			update
			;;
		h)
			usage
			;;
		*)
			usage 1
			;;
	esac
done

eval "$script -h"
exit 0
